
### PUT
PUT http://localhost:3002/bp/products/212 HTTP/1.1
Content-Type: application/json

{
     "id": "212",
      "name": "abcdefgh",
      "description": "añdsifjasñldijasdf",
      "logo": "abcdefgh",
      "date_release": "2025-06-01",
      "date_revision": "2025-06-30"
}